name: Vercel Deployment

on:
  push:
    branches: [ main, develop ]
  # Temporarily disabled for pull requests until Vercel is properly configured
  # pull_request:
  #   branches: [ main ]

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        # Temporarily disabled cache due to missing package-lock.json
        # cache: 'npm'
        
    - name: Install Vercel CLI
      run: npm install --global vercel@latest
      
    - name: Install dependencies
      run: npm install
      
    # Temporarily disabled tests due to configuration issues
    # - name: Run tests
    #   run: npm run test
      
    - name: Run type check
      run: npm run type-check
      
    - name: Run lint
      run: npm run lint
      
    - name: Pull Vercel Environment Information
      run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Build Project Artifacts
      run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
    - name: Deploy Project Artifacts to Vercel
      run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
      if: github.ref == 'refs/heads/main'
      
    - name: Deploy Preview
      run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
      if: github.ref != 'refs/heads/main'